export const QUERY_KEYS = {
    AUTH: {
        REGISTER: "USER-REGISTER",
        LOGIN: "USER-LOGIN",
        FORGOT_PASSWORD: "USER-FORGOT-PASSWORD",
        VERIFY_EMAIL: "USER-VERIFY-EMAIL",
        REQUEST_OTP: "USER-REQUEST-OTP",
        RESET_PASSWORD: "USER-RESET-PASSWORD",
        GOOGLE_LOGIN: "USER-GOOGLE-LOGIN"
    },
    USER: {
        GET_PROFILE: "GET-PROFILE",
        UPDATE_PROFILE: "UPDATE-PROFILE"
    }
}