export const QUERY_KEYS = {
    AUTH: {
        REGISTER: "USER-REGISTER",
        LOGIN: "USER-LOGIN",
        FORGOT_PASSWORD: "USER-FORGOT-PASSWORD",
        VERIFY_EMAIL: "USER-VERIFY-EMAIL",
        REQUEST_OTP: "USER-REQUEST-OTP",
        RESET_PASSWORD: "USER-RESET-PASSWORD",
        GOOGLE_LOGIN: "USER-GOOGLE-LOGIN",
        GOOGLE_CALLBACK: "USER-GOOGLE-CALLBACK"
    },
    USER: {
        GET_PROFILE: "GET-PROFILE",
        UPDATE_PROFILE: "UPDATE-PROFILE",
        SEARCH_USERNAME: "SEARCH-USERNAME"
    },
    TESTIMONY: {
        GET_TESTIMONY_FEED: "GET_TESTIMONY_FEED",
        GET_TESTIMONY_DETAILS: "GET_TESTIMONY_DETAILS",
        GET_TESTIMONY_BY_USER: "GET_TESTIMONY_BY_USER",
        CREATE_TESTIMONY: "CREATE_TESTIMONY",
        DELETE_TESTIMONY: "DELETE_TESTIMONY",
        LIKE_TESTIMONY: "LIKE-TESTIMONY",
        UN_LIKE_TESTIMONY: "UN-LIKE-TESTIMONY",
        BOOKMARK_TESTIMONY: "BOOKMARK-TESTIMONY",
        UN_BOOKMARK_TESTIMONY: "UN-BOOKMARK-TESTIMONY",
        GET_TESTIMONY_REPLY: "GET-TESTIMONY-REPLY",
        SEARCH_TESTIMONIES: "SEARCH-TESTIMONIES"
    },
    FELLOWSHIP: {
        GET_FELLOWSHIPS: "GET_FELLOWSHIPS",
        JOIN_FELLOWSHIPS: "JOIN_FELLOWSHIPS",
        LEAVE_FELLOWSHIPS: "LEAVE_FELLOWSHIPS"
    },
    TOPIC: {
        GET_ALL_TOPIS: "GET_ALL_TOPIS",
        GET_TESTIMONIES_BY_TOPIC: "GET-TESTIMONIES-BY-TOPIC"

    }
}